"""Add full_user_prompt and full_model_response to chat_messages table

Revision ID: 870aff7a8212
Revises: a269f6dcc538
Create Date: 2025-11-21 23:13:42.500656

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "870aff7a8212"
down_revision: Union[str, Sequence[str], None] = "a269f6dcc538"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_messages", sa.Column("full_user_prompt", sa.Text(), nullable=True)
    )
    op.add_column(
        "chat_messages",
        sa.Column("full_model_response", sa.Text(), nullable=True),
    )
    # Add CHECK constraint
    op.create_check_constraint(
        "check_full_prompt_response",
        "chat_messages",
        "CASE WHEN is_from_user = true THEN full_user_prompt IS NOT NULL ELSE full_model_response IS NOT NULL END",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "check_full_prompt_response", "chat_messages", type_="check"
    )
    op.drop_column("chat_messages", "full_model_response")
    op.drop_column("chat_messages", "full_user_prompt")
    # ### end Alembic commands ###
