"""add claude and chatgpt api to user schema

Revision ID: e0b077c8178a
Revises: 7854b3d166fc
Create Date: 2026-01-06 19:24:21.670930

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0b077c8178a"
down_revision: Union[str, Sequence[str], None] = "7854b3d166fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("chatgpt_api_key", sa.String(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("claude_api_key", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "claude_api_key")
    op.drop_column("users", "chatgpt_api_key")
    # ### end Alembic commands ###
